### PR TITLE
Moved runLint.sh and tagAndPublish.sh files to scripts folder

### PR DESCRIPTION
**Pull request by Muhammadwasi**
### What I did?

- Moved `runLint.sh` and `tagAndPulblish.sh` files to `/scripts` folder.
- Changed their path wherever the two scripts have been used. 

Issue #3

### CODE REVIEW

**Review by huangjien — COMMENTED** [review]
Thanks for contribute to this repo.
But according the travis security policy: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
The travis will not start on this PR. So this changes cannot be merged to our branch.

**Comment by salob** [comment]
@huangjien create a new branch for this, then change the base branch on this PR to the new one and merge. This should allow Travis to run and you can merge then as normal from the temp branch. Hope that makes sense

**Comment by Muhammadwasi** [comment]
@salob @huangjien Yes, any of the maintainers can create a PR based on this branch and then resolve this issue.

**Comment by romakarol** [comment]
Travis passed - merging to master.

Thanks for the input folks.

**Pull request merged**
